$(document).ready(function(){
    $("#contact").click(function(){
        $("#modalShow").modal('show');
    });
    $("#cvLink").click(function(){
        $("#modalCv").modal('show')
    });
    $("#profilePics").click(function(){
        $("#modalPics").modal('show');
    })
});